### PR TITLE
Issue/2112

### LINKED ISSUE #2112: User Roles and Capabilities need to be cleaned up a bit
## Issue Overview
Some Give user roles have abilities they shouldn't, some don't have abilities they should. We also need to give some of the custom Give capabilities to the default user roles.

### Updates to Give Worker
The Give Worker should be able to view all donations, but not edit them. Currently, there is a capability called `view_give_private_payments` but that alone does not allow the Give Worker to view and NOT edit the donations. There's one of two options:

1. Either update that existing capability to function as intended or create `view_give_payments` and have the donation details screen respect that.
2. Update the donation details screen to respect that capability as intended

Or maybe both.

### Updates to Accountant
If we add a new capability `view_give_payments` it needs to be added to the Give Accountant as well.

### Updates to Give Manager
The Give Manager has some capabilities that go outside the scope of Give which I believe are unexpected. Like:
* Editing, Deleting all pages and posts
* Importing/Exporting content via the WordPress Import/Export tools

To fix this, we should remove the following capabilities from the Give Manager:
* `delete_others_pages`
* `delete_others_posts`
* `edit_others_pages`
* `edit_others_posts`
* `manage_categories`
* `import`
* `export`

### Updates to Core Author
The Author expects to be able to contribute content to the website. Give Forms are also content since they have unique slugs. We should add the following capabilities to the Author role:
* `delete_give_forms`
* `delete_published_give_forms`
* `edit_give_forms`
* `edit_published_give_forms`

**NOTE:** I didn't give them `publish_give_forms`. They should be able to author, but a Give Worker, Manager, or Editor needs to approve those posts since they do have a donation form as well.

### Updates to Core Editor
Similarly to the Author, the Editor expects to be able to edit all content on the site. Currently, the Editor role cannot even view Give forms. That is unexpected. We should add the following capabilities to the Editor role:
* `delete_give_forms`
* `delete_others_give_forms`
* `delete_private_give_forms`
* `delete_published_give_forms`
* `edit_give_forms`
* `edit_others_give_forms`
* `edit_private_give_forms`
* `edit_published_give_forms`
* `publish_give_forms`
* `read_private_give_forms`

### PR DESCRIPTION
**Pull request by mehul0810**
## Description
This PR resolves #2112

## How Has This Been Tested?
I've tested this PR with the following user roles:
- Give Worker,
- Give Accountant
- Give Manager
- Author
- Editor
and made sure that the newly added capabilities work properly with the user roles.

## Screenshots (jpeg or gifs if applicable):

**Give Worker**
image

**Give Accountant**
image

**Give Manager**
image

**Author**
image

**Editor**
image

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@mehul0810 is it possible to remove the columns from view for the _author_ and _editor_ roles? They serve no purpose being there blank.

**Comment by mehul0810** [comment]
@DevinWalker Should I need to remove `Categories` and `Tags` column from the view of Author and Editor role as these columns are empty? If Yes, It is displayed empty as there are no categories or tags assigned to donation forms and the taxonomies are enabled from settings.

**Comment by DevinWalker** [comment]
@mehul0810 no those columns are fine. Hopefully if they are enabled then they will have data displayed.

**Comment by DevinWalker** [comment]
@mehul0810 I believe this PR requires an upgrade routine for current installs to reset the roles using the updated capabilities. Otherwise, the code above would only affect new installs and not existing installs.

**Comment by mehul0810** [comment]
@DevinWalker I've added upgrade routine as well as refactored some code as per discussion with @ravinderk over call. [Click here](https://www.youtube.com/watch?v=oKhEh-ZhjQU) to view the testing video.

**Comment by DevinWalker** [comment]
@mehul0810 I'm getting video unavailable.

**Comment by mehul0810** [comment]
@DevinWalker Can you please try accessing video with your WordImpress Account

**Pull request merged**
