### PR TITLE
Issue/339 - Webpack Migration

### PR DESCRIPTION
**Pull request by DevinWalker**
## Description
Many updates including:

1. Addition of Webpack to build Give package
2. Removal of bower, minified files, dependancies, and gulp
3. Introduction of a better README.md file
4. New `Give_Scripts` class

Part of #339 

### Reviewers

Please check the following:

1. Try out setup instructions: https://github.com/WordImpress/Give/tree/issue/339 Do they make sense to you?
2. Errors and bugs: Open console, any JS bugs? Are all scripts loading.
3. Add-on compatibility 
4. Do you have any suggestions? For instance, ways to make code cleaner, directory structure improvements, etc?

### Known Issues
- [x] POT file generation
- [x] `cross-env` for Windows setups
- [x] Donation Importer is broken
- [x] Unit tests not working

## How Has This Been Tested?
- Manually & Unit Tests

## Types of changes
- Code Improvement

### CODE REVIEW

**Comment by mehul0810** [comment]
@DevinWalker We need to manage `.pot` files for translations using WebPack as well. Similarly, we used to do using Gulp. As per discussion over slack, we need to code that in the production build workflow.

**Comment by kevinwhoffman** [comment]
Let's make sure to test across operating systems (Mac/Windows/Linux). If we need to provide OS-specific build scripts, this is a helpful package to do so. https://www.npmjs.com/package/run-script-os

**Comment by kevinwhoffman** [comment]
This package may also be helpful for Windows since we are using environment variables. https://www.npmjs.com/package/cross-env

**Comment by DevinWalker** [comment]
Note: @mehul0810 this commit takes care of POT file generated using the same package we were previous using without the gulp wrapper: a31df99d4a277c11c808a3e23ae7b2db28e3854c

**Comment by emgk** [comment]
I and @jaydeeprami followed instruction for development https://github.com/WordImpress/Give/tree/issue/339#local-development in our system ( Windows 8/64bit ).

When running command `npm install` at the end of its result it shows follwing:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
```
Since [`fsevents`](https://www.npmjs.com/package/fsevents )  required in macOS only, So, we think its okay to ignore this warning in win/linux os. https://stackoverflow.com/a/40464936

When running command `npm run production` shows this below message:

```
> give@2.1.0 production C:\Users\MD-multidots\Local Sites\give\app\public\wp-con
tent\plugins\Give
> NODE_ENV=production webpack

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! give@2.1.0 production: `NODE_ENV=production webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the give@2.1.0 production script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above. 

```
As @kevinwhoffman said in above we have included [cross-env](https://www.npmjs.com/package/cross-env) and changed production script to 

>  `"production": "cross-env NODE_ENV=production webpack",` 

working fine.

**Comment by DevinWalker** [comment]
@emgk @kevinwhoffman I've added `cross-env` to `package.json`. It should be smoother sailing now for Windows users. See d0c4bff8d83d5c7760371b8ebd8cb6f8c8345684

**Comment by emgk** [comment]
@DevinWalker I have tested the latest changes of cross-env and its working fine. 👍

**Pull request merged**
