### PR TITLE
Fix(polylang): change hooks priority so that polylang get load first #2784

### LINKED ISSUE #2784: fix(compat): resolve conflict with Polylang plugin
## Issue Overview
The Polylang plugin languages revert to English on switching between payment gateways.

## Expected Behavior
If the language for a form is set at the form level, switching between payment gateways should not trigger a different language.

## Current Behavior
polylang

## Steps to Reproduce (for bugs)
On Local By Flywheel:
1. Download this zip file, and drag/drop it onto local by flywheel. https://drive.google.com/file/d/1lxJLvFbfWyk0T3ikZnzzLAEhfBIJWksh/view?usp=sharing
2. Log into the site with username ben and password 1
3. Navigate to http://polylang.local/fr/donations/french/
4. toggle between the donation forms. 

Or the long way:
1. Install Give and polylang. ( https://wordpress.org/plugins/polylang/ )
2. Set up two languages, english and French in the polylang settings.
3. create two forms, one in each language. Make the second one a translation of the first.
4. Navigate to the French version.
5. switch the payment gateway.

## WordPress Environment
<details>
### WordPress Environment ###

Home URL: http://polylang.local
Site URL: http://polylang.local
WP Version: 4.9.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: polylang.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.2
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://polylang.local/donation-confirmation/
Failure Page: http://polylang.local/donation-failed/
Donation History Page: http://polylang.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Polylang: by Frédéric Demarle – 2.3

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to resolved #2784 

## How Has This Been Tested?
Manually Tested 

## Video/Screenshots (jpeg or gifs if applicable):
Video Link: https://screencast-o-matic.com/watch/cFnj37o5UU

image

## Types of changes
<!-- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ravinderk** [comment]
@raftaar1191 did you check this pr with FFM, recurring and other payment gateways because changing `plugins_loaded` hook priority can be crucial or break the code.

**Comment by raftaar1191** [comment]
@ravinderk I had an check with most of the payment gateway as well as with FFM and recurring donation Add-on its working fine and great

**Comment by ravinderk** [comment]
@DevinWalker I am not in favor of increment or decrement of `plugin_loaded` priority. This pr will resolve the issue but can affect other add-ons.

Personally `plugin_loaded` is not a good place to load plugin if we want to prevent future conflict then we have to load plugin before `plugin_loaded`.
For ref: https://github.com/ravinderk/Give/commit/f77b303032d75f4310336f44254cc28aa1c51abb

We can contact with Polylang team to quickly resolve or get some clue because it will take time to understand this plugin.

**Comment by raftaar1191** [comment]
@ravinderk 

I had an test with Give Addd-on everything is fine, but it may be the case that the third party add-on may get break because of this

**Comment by DevinWalker** [comment]
Rather than changing priorities here I'd also rather go the route ravinderk/Give@f77b303

**Pull request closed without merging**
