### PR TITLE
Add setting to set number of decimal points shown and saved in prices

### PR DESCRIPTION
**Pull request by ravinderk**
Related to: https://github.com/WordImpress/Give/issues/738

Screenshots:

screen shot 2016-07-25 at 3 27 10 pm
screen shot 2016-07-25 at 3 27 27 pm
screen shot 2016-07-25 at 3 27 36 pm
screen shot 2016-07-25 at 3 27 43 pm
screen shot 2016-07-25 at 3 27 56 pm
screen shot 2016-07-25 at 3 28 04 pm
screen shot 2016-07-25 at 3 28 28 pm
screen shot 2016-07-25 at 3 28 37 pm
screen shot 2016-07-25 at 3 28 40 pm

### CODE REVIEW

**Comment by ravinderk** [comment]
As discussed with @DevinWalker, we found following issues:
1. Amount rounding is not working fine if number of decimals value is zero.
2. Donation amount is wrong ( after donation purchase) if set donation amount value with  three decimals and number of decimals value is three.
screen shot 2016-07-25 at 11 17 58 pm
screen shot 2016-07-25 at 11 18 05 pm
screen shot 2016-07-25 at 11 18 21 pm
screen shot 2016-07-25 at 11 18 22 pm
screen shot 2016-07-25 at 11 18 36 pm

**Comment by DevinWalker** [comment]
As we discussed:

1. When zero `0` is saved in the setting it causes issues - can be resolved by setting the default option upon install to `2` and defaulting to `0` in `give_get_option`

2. When `3` is saved as the decimal spaces option the amounts are rounding incorrectly

**Comment by DevinWalker** [comment]
@ravinderk are we good here?

**Comment by ravinderk** [comment]
@DevinWalker This pull request need to test more, so i am close this for now and create new pull request when i am done with some research and testing.

**Comment by DevinWalker** [comment]
Sounds good

**Pull request closed without merging**
