### PR TITLE
feat(modal): create modal API to replace JS alerts #1475

### PR DESCRIPTION
**Pull request by Sidsector9**
Related #1475 

## Description
This feature implements an API for [magnific popup](http://dimsemenov.com/plugins/magnific-popup/).
All popups live under `GiveModal` class.

### Structure
```
new GiveModal() . [ popup type ] . [ addButton() ] . [ addFilter() ] . [ customContent() ]. popup()
```
The GiveModal API supports method chaining. Everything you see above inside square brackets can be chained in **_any order_** and they are **_optional_**.

An example of method chaining would be:
```js
new GiveModal()
        .notice()
	.customContent( 'This is a demonstration of method chaining with extra buttons.' )
	.appendButton( 'visit-site', 'primary', 'Visit Site', 'visitSiteCallback' )
	.popup();
```
which will produce a popup as: 
chaining

### Popup Types

For an HTML content to be shown as popup, there are 5 types of popups: 
```html
<div id="test-popup" class="white-popup mfp-hide">
	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam repellendus, sequi quaerat, nobis aperiam officia magni, dignissimos inventore harum asperiores quasi commodi explicabo corrupti, tempora voluptatum vitae aut expedita. Non!
</div>
```

#### 1. **Default**
default
This can be instantiated using:
```js
new GiveModal( '#test-popup' ).popup();
```

#### 2. **Success**
success
This can be instantiated using:
```js
new GiveModal( '#test-popup' )
	.success()
	.popup();
```

#### 3. **Warning**
warning
This can be instantiated using:
```js
new GiveModal( '#test-popup' )
	.warning()
	.popup();
```

#### 4. **Notice**
notice
This can be instantiated using:
```js
new GiveModal( '#test-popup' )
	.notice()
	.popup();
```

#### 5. **Error**
error
This can be instantiated using:
```js
new GiveModal( '#test-popup' )
	.error()
	.popup();
```

### Add custom buttons
You can add more buttons to the popup using the `appendButton()` method. This method internally uses the `GiveModal.filter.add()` method to add more buttons.

### Filters
`GiveModal` API provides filter hooks for JavaScript. In the course of developing this API, you can create more filters using `GiveModal.filter.apply()` method and then using the `GiveModal.filter.add()` method to hook callbacks on the filter hook.

## How Has This Been Tested?
Manually tested

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by Sidsector9** [comment]
@DevinWalker @ravinderk I have a feedback request for you.
IMHO, we can replace the header text (Error, Success, etc..) with images or animated SVGs.
Let me know your views on the implementation of this API.

**Comment by kevinwhoffman** [comment]
## Design Feedback

Good progress, @Sidsector9. Regarding design, we ought to follow WordPress core conventions so that our UI blends in more seamlessly. To accomplish that, we can think of these modals as oversized admin notices. Here are my recommendations:

- Remove `Success`, `Warning`, `Notice`, `Error` headings
- Add 4px left border to match WordPress core notices (see image below)
- Use WordPress notice colors for the left border
    - success - `#46b450`
    - warning - `#ffb900`
    - error - `#dc3232`
    - info - `#00a0d2`
- Use WordPress button styles
    - `button-primary` - primary blue button style
    - `button` - secondary gray button style
- Set line height of body text to 1.5 for readability

image

**Comment by DevinWalker** [comment]
Here's the design direction I'm thinking:

## Default Modal

modal overlay - default

## Success Modal

modal overlay - success

## Warning Modal

modal overlay - warning

--- 

You get the point about the top border color setting the modal mood depending on the color, similar to how WP notices work.

**Comment by kevinwhoffman** [comment]
@Sidsector9 Devin and I discussed the design. Please use his mockups above as reference with the following changes.

- Align the buttons to the right of the modal as shown below.
    - Place the secondary button first, using the gray `button` class.
    - Place the primary button second, using the blue `button-primary` class.
- When the modal first opens, the secondary button should have focus as indicated in the mockup.

image

**Comment by DevinWalker** [comment]
Another note to add to above:

* Keyboard tabbing should work as expected similar to how the JS native window confirm works. First it hightlights the "Cancel" button then tabbing highlights "OK" and pressing enter confirms.

**Comment by kevinwhoffman** [comment]
@ravinderk Please review code and report findings here. Thanks.

**Comment by Sidsector9** [comment]
@DevinWalker @kevinwhoffman I've made the necessary changes, can you have a look at this -
https://drive.google.com/file/d/152LXmKCviSLo6a0NXKe7WHbRjlXTJ65v/view

**Comment by DevinWalker** [comment]
@Sidsector9 thanks for the video. It's looking much nicer now.

Please replace all core native JS notices with this functionality so we can see it in action.

**Comment by Sidsector9** [comment]
I have trouble simulating JavaScript's `alert` dialog. **alert**, **prompt** and **confirm** halt page execution and make the interface inaccessible until you close the dialog. Turns out, JS does not provide an API to halt the execution.

Check this scenario:

1. Clicking on an anchor tag will redirect you to the said page
2. We can use `e.preventDefault()` to disable redirection and show our popup and depending on the user input (OK, Cancel) , we can redirect.
3. But suppose if we have a callback on the `onbeforeunload` event, inside which we wish to popup our custom alert box, here we can't stop it from redirection occurring due to anchor tag. Do you guys have any workaround?

**Comment by DevinWalker** [comment]
@Sidsector9 in some cases we will still have to use native `alert` when necessary. This modal API doesn't have to be an exact replacement but will give us a great utility to use throughout the plugin in where necessary in the future.

**Comment by Sidsector9** [comment]
@DevinWalker I have replaced native alert dialog on the donors and donation's listing page, please check it:  https://www.useloom.com/share/4dae8e64c6894d2d86b37dc312823f27

**Comment by raftaar1191** [comment]
Nice @sidsector9 


It really look awesome

**Comment by ravinderk** [comment]
> Slack Call Summary
> 
> Participants: @Sidsector9 , @ravinderk
> Topic: Review Modal API
> Result: Modal API is not robust yet for use. I will work on this tomorrow to improve this pr.

**Comment by DevinWalker** [comment]
### Native alerts should have a main heading

The alerts displayed in @Sidsector9 look a bit bare and unattractive:





### Modal Improvement Requests

1. Most modals should be of the type "warning" unless informational or confirmation. In the video you have linked to above _all_ the modals you demonstrate should be of the "warning" type. This is because you are attempting to do something that is not possible. Thus, you should be warned. Make sense?

2. Most modals should have a proper heading before the main text. For instance, if you attempt to delete a donor without selecting a donor like the screenshot above then the title would be `No Donor(s) Selected`. Also, this is modal should be a warning type.

**Please re-review all the native alerts/confirmations you have modified while keeping the change requests I made above.**

**Comment by ravinderk** [comment]
@DevinWalker If you check Modal API calling structure. It is looking like this 
```
new GiveModal() 
   . [ popup type ]
   . [ addButton() ]
   . [ addFilter() ]
   . [ customContent() ]
   . popup()
```
It does not accept any `object` that means it is hardly coupled with `magnifypopjs`. In future, it will be difficult to switch pop plugin because we are not accepting object in `GiveModal` class.
And also coding of Modal API can be with `class` (es6).

**Comment by Sidsector9** [comment]
@DevinWalker I got your point. I'll work on the feedback.

@ravinderk That was my goal that the developer shouldn't have to deal with configuration by passing objects, instead go by functions.

The `popup()` function is the function that will pass the final configured object to Magnific Popup. All the remaining functions like `success()`, `error()` will just configure the object that will me merged inside `popup()` for final use. If you need more functionality, create another chainable function that will add more configuration to the object and so on...
This was the code looks neat because you don't have to deal with objects and just functions.

**Comment by ravinderk** [comment]
@Sidsector9  Why adding so much chainable function when we can achieve same with a simple structure.
@Sidsector9  Can you explain how we can move from magnifypopup to another if want to ( not major but still keep in mind)?

**Comment by ravinderk** [comment]
@sid can you confirm that this pr ready to review for @devinwalker and @kevinwhoffman

- [ ] make sure this pr working fine on firefox and IE
- [ ] convert all possible alert and confirm to modal

**Comment by Sidsector9** [comment]
- Go to the **Donations** page - `/wp-admin/edit.php?post_type=give_forms&page=give-payment-history`

The following popups are replaced with GiveModal API:

  1. Click the **Apply** button (Warning)
  2. Select any **bulk action** and then click **Apply** (Warning)
  3. Select a **donation** and select a **bulk action** and then click **Apply** (Confirm)
  4. Hover over a donation and click **delete** (Confirm)
  5. Hover over a donation and click **resend receipt** (Confirm)

---

- Go to the **Donors** page - `/wp-admin/edit.php?post_type=give_forms&page=give-donors`

The following popups are replaced with GiveModal API:

  1. Click the **Apply** button (Warning)
  2. Select any **bulk action** and then click **Apply** (Warning)

---

- Go to the **Settings** page - `/wp-admin/edit.php?post_type=give_forms&page=give-settings`

  1. Change a setting and navigate to another page, you will see a confirm prompt like this:

unsaved

This prompt is not replaced because it blocks the page execution on `onbeforenload` event. [See this](https://snag.gy/wXxCjM.jpg)

---

- Go to the **Tools** page inside import
The alert boxes for `success` and `error` are untouched because the JS logic is written inside [class-give-import-donations.php](https://github.com/WordImpress/Give/blob/release/2.1/includes/admin/tools/import/class-give-import-donations.php#L369) file, which does not detect `GiveModal()` function.

This will require refactoring the code to move the JS code from the PHP file to `admin-scripts.js` file. I need confirmation to go ahead with this.

CC: @ravinderk, @kevinwhoffman @DevinWalker

**Comment by Sidsector9** [comment]
**Call Summary**
**Participants**: @emgk and @Sidsector9
**Topic**: Test GiveModal API on Internet Explorer browser
**Result**: Govind and I have tested GiveModal on Internet Explorer, the findings are:

- Till IE10, GiveModal has full support.
 - IE versions below 9 have partial support, as in , the modal does not support CSS3 transform animations. On triggering the popup, the modal will just show/hide instead of animating.

**Comment by Sidsector9** [comment]
This is a followup for **Tools page modals**

After merge of PR #2995 into release/2.1, the `alert()` dialog in CSV/JSON importer have been replaced with GiveModal. This PR is ready for testing and merge.

CC: @ravinderk @DevinWalker

**Pull request merged**
