### PR TITLE
Feature/floatlabels #204

### PR DESCRIPTION
**Pull request by pryley**
#204 : Uses my float-labels.js plugin: http://geminilabs.github.io/float-labels.js/

### CODE REVIEW

**Comment by mathetos** [comment]
Paul that link seems to be down. Do you have an active link to see a demo of the Float labels?

**Comment by DevinWalker** [comment]
Thanks for the PR. Question: Are the floating labels enabled by default or is there an option to enable them?

**Comment by pryley** [comment]
I added an option to enable them:

screenshot 2015-09-04 00 26 45

I will put up a live example soon, for now here is a screenshot with the twentyfifteen theme enabled:

screenshot 2015-09-04 00 28 35

**Comment by pryley** [comment]
@mathetos The link should work now. There is no live example at the moment, just instructions on usage.

**Comment by DevinWalker** [comment]
Hey @pryley how come here https://github.com/WordImpress/Give/pull/231/files#diff-143c1ae2e57a1cf5852d709be4b5aa85L531 you change the input to type `tel` for CC fields?

**Comment by pryley** [comment]
@DevinWalker `tel` input types show the numeric keyboard on mobile devices.

Reference: http://mobileinputtypes.com/

**Comment by DevinWalker** [comment]
Cool! I figured. So, I just took a look at this and it's a really great PR. Did you get a chance to run a few test transactions through the new CC fields to verify they pass to the gateways in a valid format still? I had an issue with the recent credit card mask upsetting PayPal with extra spaces in the CC fields. I just want to ensure we don't disrupt the way the fields are currently passed.

**Comment by pryley** [comment]
I took a quick look at the output of the `give_get_purchase_cc_info()` function which builds the CC array and everything looked fine, from looking at the code that seemed to be the area to verify.

**Comment by pryley** [comment]
A few things to consider:

1. Changing the input types to `tel` is great for accessibility, but the Twenty Fifteen Wordpress theme (and maybe the others also) does not include css styles for that type, so when the theme is enabled and the `float labels` option is disabled, the form looks like this:

screenshot 2015-09-04 01 39 01

This is Wordpress' fault as their theme styles are incomplete.

2. With `Float Labels` enabled, the select styling will likely not match all themes (borders, background, etc.). It may be necessary to have a slightly more opinionated view on the default Give form styles.

3. The `Float Labels` Select angle-down icon is css generated. You may want to use a icon font instead (i.e. add an `angle-down` icon to the icomoon font).

**Comment by DevinWalker** [comment]
That's ok with the style concern. I'm going to touch up the styles anyways for 1.3.

**Pull request merged**
