### PR TITLE
Issues 2263

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR for issues #2263 

## How Has This Been Tested?
Test the layout with the donation in it and also after deleting all the donation within it and with the Add-on as well 

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@ravinderk @DevinWalker 

Please review & merge the PR request

**Comment by ravinderk** [comment]
@raftaar1191 @kevinwhoffman  I am getting weird button on empty form listing

screen shot 2017-11-07 at 8 28 49 pm

**Comment by raftaar1191** [comment]
@ravinderk 

I tried this with old as well as by creating new instance but was not able to regenerate the issues 

I have also checked the URL that you send it with the screenshot 
image

I have also check with the diff-diff version of WordPress Core from 4.8 to 4.8.3.
I have also check with the Give Add-on as well as without the Give Add-on


@ravinderk 
Can you try to regenerate the issues on another site and as well the step from which you are deleting the Donation Form

**Comment by kevinwhoffman** [comment]
The `Empty Trash` button only appears when there is a form in the trash, so you'll likely need to create a form and then trash it to recreate the issue. Then look at the CSS class used to wrap the button and add it to the list of classes that are hidden.

**Comment by raftaar1191** [comment]
Thanks @kevinwhoffman I will check that too

**Pull request merged**
