### PR TITLE
Issues 2420

### LINKED ISSUE #2420: IMPORTER: Donations are being inaccurately marked as duplicates
## Issue Overview
Donations are being inaccurately marked as duplicates.

## Expected Behavior
When a CSV file is imported, and the donations are from the exact same donor but on different dates, they should all be imported.

## Current Behavior
Currently, it appears only the FIRST donation from a donor is imported and all others are treated as duplicates even though the donations occured on different dates.

## Possible Solution
I believe these lines here are either malforming or misconstruing the date formats for imported donations: https://github.com/WordImpress/Give/blob/release/1.8.17/includes/import-functions.php#L684-L685

## Steps to Reproduce (for bugs)
1. Ask me for the CSV file I've been working from
2. Map the fields like so:
givewp-mapped-fields
3. Run the import
4. You'll get around 129 duplicates when there are only 22 duplicates total.

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to resolve #2420 

## How Has This Been Tested?
Manually Tested By adding the donations. Please see the video for more information that how it's being tested 
Video: http://screencast-o-matic.com/watch/cbXUru2yMy

CSV Link:
https://givewp.slack.com/files/U064V9KDJ/F865UL2JF/pawm-import-edited.csv

https://docs.google.com/a/wordimpress.com/spreadsheets/d/15A9d2yY8UeLBBZ38iSGgiHvr6RQ7K0Hg1_P9NHYiP-c/edit?usp=sharing

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@mathetos can you review this PR?

**Comment by mathetos** [comment]
@DevinWalker @raftaar1191  Just reviewed this. Here's the results I got:

image

All the numbers that are listed out below are accurate according to the CSV file. But there are a few discrepencies:

1) The very top number "1304 donations processed" -- I have no idea why I would have a different number there than Deepak did, particularly since it seems that that number isn't a combination of the items listed (which would be 999) and it's definitely not the total of the donations (which would be 493).  I'm not sure how you might replicate this, but it would be worth digging into how that number is generated and confirm that it's accurate (or maybe just remove it completely, I'm not sure it's useful in general anyway)

2) For some reason, on this PR, the donation details links are gone. See here:
image

3) Lastly, I know that when there are two different donor names associated with the same email address that we don't link their names the second time, but in this case it seems that we don't link it the second time, but we create two different donor profiles. I'm not 100% certain that that's intentional or not.
image

**Comment by raftaar1191** [comment]
@mathetos 

I had a look at your commit 
1> The very top number "1304 donations processed"
-> The Donation Form that you are using has CSV id till 1304 of which only 500 are fields with donation rest all are empty
image



2> For some reason, on this PR, the donation details links are gone. See here:
-> This is because of Permission issues ( The user from which you are viewing the donation details does not have the permission to view the single donation and donor details  )
Please try creating a new user and then have a look.

This can be an issue with the Give User Role as in Version `1.8.17` Give Role is also getting setting up


3> 
-> did not get you properly but What I see in this is the email id is diff for both of the donor so two diff donor would be expected 

Let me know you thought on this @mathetos

**Comment by mathetos** [comment]
@raftaar1191 
1) That makes sense
2) No, it was an admin account -- please double-check
3) Apologies, I screenshot the wrong thing.  I don't understand why the donations associated with "Jeff and Kathleen" are linked in this way. There are no other donors with that email address, but their names are linked strangely. See here:
image

**Comment by raftaar1191** [comment]
@mathetos 

2> I just had and check my old sites as well as I creating a new one as well not able to regenerated the issues 
image

Can you send me the **Get Sites Details** and **Export Give Settings** so I can have a better look


3> Please see this video this is not because of the Importer it's can be replicate in Give Core itself, So I am creating a new issue for this 
http://screencast-o-matic.com/watch/cbXviU243D

**Comment by raftaar1191** [comment]
@mathetos 
Here is the issues that I have create https://github.com/WordImpress/Give/issues/2437

Please commit on it if you have any suggestion

**Comment by raftaar1191** [comment]
@mathetos 

https://github.com/WordImpress/Give/pull/2434#issuecomment-348038249 Point Number 3
Here is the PR for the issues that you have mention https://github.com/WordImpress/Give/issues/2356

**Comment by mathetos** [comment]
@raftaar1191 Got it, that all makes sense. Now that I'm testing on 1.8.17 and have run the upgrade routine I can see item 2 working, and item 3 makes sense to me too.

**Comment by raftaar1191** [comment]
@ravinderk @DevinWalker please review and merge the issues

**Comment by DevinWalker** [comment]
@raftaar1191 how come unit tests are failing? Can you resolve those prior to us reviewing?

**Comment by raftaar1191** [comment]
@mathetos 

I try to regenerate the issues at my ends also try with old and by creating a new sites but not able to regenerated the issues

**Comment by DevinWalker** [comment]
@raftaar1191 @mathetos what's the status here? Should I step in and test as a third party?

**Comment by DevinWalker** [comment]
I just tested it and it's working like expected. See video: https://goo.gl/1gmb8F

I'm merging. @mathetos if you find anything please create issues for them.

**Pull request merged**
