### PR TITLE
Diagram WP/Give DB structures

### PR DESCRIPTION
**Pull request by drzraf**
## Description
Added a text file for documentation purpose
Documented some of the references / _foreign_ keys used between WP and Give.

## How Has This Been Tested?
The change is unrelated to code but just attempt document how entities, stored in the RDBMS, relate to each other. This is especially useful when it comes to custom fields and choosing the right destination entity metadata.

## Types of changes
neutral: documentation-only

### CODE REVIEW

**Comment by DevinWalker** [comment]
Hey @drzraf thanks for the PR but I think this is something we would rather see on givewp.com within the developer docs. Is this txt file an export from Sequel Pro, or how did you create this?

**Comment by drzraf** [comment]
http://asciiflow.com/
(you can import/export the text file there)

**Comment by drzraf** [comment]
Hi @DevinWalker, did you push this somewhere?
What about the future of Give's data structures?

**Comment by DevinWalker** [comment]
@drzraf would love to chat more with you on this in Slack. Please join us: https://givewp.com/join-us-slack/

**Comment by drzraf** [comment]
out of curiosity, an IRC #channel out there?

**Comment by DevinWalker** [comment]
Sorry @drzraf no IRC channel, only Slack.

**Pull request closed without merging**
