### PR TITLE
Feature: 1. Form-specific float-labels option / 2. Extended shortcode attributes

### LINKED ISSUE #271: Floating Labels Get Messed Up with Multiple Donation Forms on a Single Page
When multiple forms are on a single page the floating labels get messed up.
9-22-2015 3-06-33 pm
9-22-2015 3-06-25 pm

### PR DESCRIPTION
**Pull request by pryley**
__1. Adds a float-label option to forms, widget, and shortcode.__

Also refactored the widget code.

__2. Shortcode attributes for [give_form]__

Implements: #165 (I also added an attribute for float-labels)

- [x] show_goals="true/false"
- [x] show_title="true/false"
- [x] show_content="true/false"
- [x] float_labels="global/local/enabled/disabled"
- [x] display_style="onpage/reveal/modal"

---

I'm resubmitting the shortcode pull-request as it is related to the float-labels option (in the shortcode).
This also subsequently fixes #271 and #272 as float-labels.js has been updated to [v1.0.7](https://github.com/geminilabs/float-labels.js#changelog).

### CODE REVIEW

**Comment by pryley** [comment]
@DevinWalker Also regarding your question about passing $args through many functions, I replied on the old pull-request [here](https://github.com/WordImpress/Give/pull/268#issuecomment-142991985).

I also created a function for extracting the form_id from $args in /includes/forms/functions.php:24 (`get_form_id_from_args()`).

**Comment by pryley** [comment]
I added the [give_form] shortcode attribute options to the thickbox modal. 

I added the css inline so it only loads on that page. I also did some opinionated styling on the thickbox modal frame. These styles are grouped together in case you think they shouldn't be there.

This is what it looks like:
screenshot 2015-09-25 22 36 25

And this is what it looks like without the thickbox frame styles:
screenshot 2015-09-25 22 54 53

**Comment by mathetos** [comment]
Sheesh Paul! Seriously nice work again. You're going above and beyond here!

**Comment by DevinWalker** [comment]
Wow. Just wow. Lovely :)

**Comment by pryley** [comment]
Unfortunately I don't think the thickbox frame styling can be used as it changes the thickbox width and height for any other shortcode buttons that use the thickbox for a modal.

If it was a button in the TinyMCE editor then TinyMCE popups could be used which look a lot better then the old thickbox modal. Alternatively, perhaps magnific-popup could be used instead...

I'll look into it tomorrow.

**Comment by DevinWalker** [comment]
@pryley honestly...  I strongly dislike thickbox. In our other plugins I've just used magnific popup for the shortcode generator. For this one, I forked over from EDD's shortcode builder so that's why it's using thickbox. Ideally, we'd swap it out for magnific.

**Comment by pryley** [comment]
@DevinWalker Would you please test the shortcode popup?

screenshot 2015-09-27 00 56 10

**Comment by DevinWalker** [comment]
@pryley definitely! I'm eager to get my hands on it. We are at WordCamp Los Angeles this weekend but when I get back tomorrow I'll test it out first thing.

**Comment by pryley** [comment]
Going to do a little more work on the shortcode class and scripts so that it can be used for multiple shortcodes.

**Comment by pryley** [comment]
image

image

image

image

image

**Comment by DevinWalker** [comment]
wonderful! :heart_eyes:

**Comment by pryley** [comment]
image

**Pull request merged**
