### PR TITLE
fix(admin-tools): correct exported field issues with duplicated standard fields and missing cat/tag filter #3047

### LINKED ISSUE #3047: fix(admin-tools): correct exported field issues with duplicated standard fields and missing cat/tag filter
## User Story

1. As an `admin`, I want `fields` to be listed clearly so that `exporter` is reliable.
2.  As an `admin` I expect fields to not be duplicated between the "standard" and "hidden" fieldsets.

**See video:** https://goo.gl/jo29Jj

## Description 
We are going to filter the donation in the following way
1. Admin will select the Cat and Tag
2. Now depending on the Cat and Tag the List of Donation Form will be shown in the Dropdown
3. If Donation Form is selected then the show the `Form Field Manager Fields, Custom Field Columns: and Hidden Custom Field Columns` and if no donation form is select then don't show this fields 

## Tasks
- [x] Add Taxonomy to Donation Form 
- [x] Make Donation Form search ajaxify 
- [x] Make Taxonomy search ajaxify 
- [x] Show Donation Form Based on Taxonomy
- [x] Add Company Name Column 
- [x] Remove duplicate fields 

## Current Behavior
Some standard columns have issues while others don't.

## Visual 
image

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to fix #3047 #3072 #3048 

## Tasks
- [x] Added Taxonomy to Donation Form 
- [x] Made Donation Form search ajaxify 
- [x] Made Taxonomy search ajaxify 
- [x] Show Donation Form Based on Taxonomy
- [x] Added Company Name Column 
- [x] Added Currency Code Column
- [x] Added Currency Symbol Column
- [x] Remove duplicate fields 
- [x] Remove Currency symbol from **Donation Total** head  

## How Has This Been Tested?
Manually Tested

## Screenshots (jpeg or gifs if applicable):
Video Link: https://screencast-o-matic.com/watch/cFfqhVbfbF

image

image

image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
## Review Findings

It's looking pretty decent @raftaar1191 but I see a few items that need addressing:

## 1. Filter by Donation Form should be the first row



## 2. Adding a cat/tag shouldn't jump height of the field - UI issue

See how the fields jump when adding a tag to the empty input:



## 3. Remove backslashed escaped characters

**Comment by raftaar1191** [comment]
@DevinWalker for Point number one

1. Filter by Donation Form should be the first row
-> We are sorting the donation form based on Categories and Tags so it won't be a good idea to shift the Donation Form above the Categories and Tags row 


Video Link: https://screencast-o-matic.com/watch/cFfqhVbfbF

**Comment by DevinWalker** [comment]
Thanks for explaining that to me @raftaar1191 - consider point 1 taken care of.

**Comment by raftaar1191** [comment]
@DevinWalker like to get on a call with you on

## 5. Add Columns to better organize the "Standard Columns":

exporter columns

**Comment by raftaar1191** [comment]
@DevinWalker 
I am not sure about the **Standard Column fields** that are going to display under which `Donation Payment Fileds`, `Donation Form Fileds` and  `Donor Fileds` 
So will first send a PR and sort the fields by me and then send the PR for review 

You can then review this PR and let me know that all the fields are in the proper subgroup or not

**Comment by raftaar1191** [comment]
@DevinWalker I updated the PR as being suggested by you in the above [comment](https://github.com/WordImpress/Give/pull/3066#issuecomment-382993261) 

## Visual 
image

**Comment by ravinderk** [comment]
@raftaar1191 Donation form dropdown is not getting updated properly

xdpj5qolpa

**Pull request merged**
