### PR TITLE
Fix issue #2152

### LINKED ISSUE #2152: PDF of Donations and Income reports not support for various currencies
## Issue Overview

When we Download a PDF of Donations and Income reports for the various currency then it's not output properly.

## Expected Behavior
- It should display currency properly for all currencies.

## Current Behavior
- Currently, It does not display output for few currencies like below:
-  INR (Indian Rupee)
- Pound etc.

## Issue Screenshot
1. When INR Currency: 

inr

2. When Pounds Sterling (£),

screenshot--2017-09-29-16-39-36-603

## Possible Solution
- We are using FPDF for generating PDF and used 'Helvetica' font. so that font not supported.
- For solution used 'dejavusans' font to support all currencies.
- For  'Iranian Rial', use 'CODE2000' font to support it.

## Steps to Reproduce (for bugs)

1. Go to Tools > Export > Click on Generate PDF (When Currency selected as USD it's work)
2. Go to Tools > Export > Click on Generate PDF (When Currency selected as INR it's not work)
3. Go to Tools > Export > Click on Generate PDF (When Currency selected as £ it does not display proper currency output)

@ravinderk, Do you want me to fix it and send PR?

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by jaydeeprami**
## Description

This PR will fix #2152 

## How Has This Been Tested?
- Tested layout after implement TCPDF
- Tested with all currencies
- Tested with Gift Aid, Tribute and PDF Receipt Addon (Using TCPDF)

## Types of changes
- Removed FPDF lib
- Implement TCPDF lib and load through composer
- Fixed design and layout after implement TCPDF
- Fixed amount format issue
- Display the proper error message if autoload.php file not exist.

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by jaydeeprami** [comment]
As discussion with @DevinWalker, I will not use Composer and load TCPDF lib directly.

**Comment by DevinWalker** [comment]
@jaydeeprami is this ready for review now? I see you're now including the package.

**Comment by jaydeeprami** [comment]
Yes @DevinWalker it's ready for the review.

**Comment by DevinWalker** [comment]
Thanks 🕺🏻

**Comment by ravinderk** [comment]
@jaydeeprami I am facing some issue while generating pr. Please check this pdf file.
[give-report-2017-10-10.pdf](https://github.com/WordImpress/Give/files/1370512/give-report-2017-10-10.pdf)

**Comment by jaydeeprami** [comment]
Thanks @ravinderk, I have fixed page break issue as well as tested with both Category and tag enable and fixed alignment, column height issue.

[give-report-2017-10-10 (12).pdf](https://github.com/WordImpress/Give/files/1371342/give-report-2017-10-10.12.pdf)

**Comment by ravinderk** [comment]
@jaydeeprami It will be very useful if graph always outputs on the new page. Let me know if you have any question


screen shot 2017-10-10 at 3 17 15 pm

**Comment by jaydeeprami** [comment]
Sure @ravinderk, I will work on it and update you.

**Comment by jaydeeprami** [comment]
@ravinderk, I have done changes. Please check it.

**Comment by ravinderk** [comment]
@jaydeeprami Please make sure font color should be same in pdf with any core setting.
Currently color changes with `Iranian Rial`.


screen shot 2017-10-10 at 3 41 54 pm

**Comment by jaydeeprami** [comment]
@ravinderk, As I have discussed with you that it's font-family issue. I have used 'CODE2000' font for the Iranian rial and Russian Rubbel and for other fonts, I have used 'Dejavusans'. 

I have applied black color for both of them as well as apply the Bold effect when Iranian rial and Russian Rubble currency used so it will match. I have tried all the possible solution to match the color. Finally, It looks like below:

1) PDF looks like when Other Currency except for Iranian rial and Russian Rubble:
[give-pdf-with-indian-currency.pdf](https://github.com/WordImpress/Give/files/1371672/give-pdf-with-indian-currency.pdf)

2) PDF looks like when  Iranian rial and Russian Rubble:
[give-pdf-with-iranian-rial.pdf](https://github.com/WordImpress/Give/files/1371673/give-pdf-with-iranian-rial.pdf)

I have tested below cases:
1. Test with all currency
2. Test with Category enable
3. Test with Tag enable
4. Test with Category and Tag both enable
5. Test with Multiple forms listing on a PDF
6. Multiple Category and tags added to make sure that alignment of height proper.
7. Test with bigger Form name to make sure that text not overlap
8. Test Graph
9. Test with all forms empty and show 'No forms found'

Thanks,

**Comment by jaydeeprami** [comment]
@ravinderk, I have checked formatting with Rial and it's not support formatting in core. I have attached the screenshot for the same.

1) Setting:
setting


2) Setting with USD:
usd-format

3) Irianain Rial:
rial-format

So Iranian Rial not supported amount formatting in Core.

Thanks,

**Comment by raftaar1191** [comment]
@jaydeeprami @ravinderk 
I have found this issues in WooCommerce as well we need to come up with and new solution to this 
image

`sprintf not working properly when the currency is change to Rial`

**Pull request merged**
