### PR TITLE
Issues/2244

### LINKED ISSUE #2244: CC fields incorrectly marking as invalid on page load
## Issue Overview
I've seen this on multiple websites now:

See: http://plf.org/give/give-form/
And HeroPress:  https://heropress.com/give/form/

## Expected Behavior
CC fields should not be highlighted if not completed incorrectly

## Current Behavior
On page load CC fields are highlight causing distraction and confusion

## Possible Solution
Review payment gateway, and attempt to reproduce the issue with same setup.

## Steps to Reproduce (for bugs)
Unknown. - Attempt to reproduce the issue.

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This Pr will resolve #2244 

## How Has This Been Tested?

By loading local site.

## Types of changes

Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@ravinderk still able to regenerated the issues 
Please used the below code and see 
https://github.com/WordImpress/Give/issues/2244


If I call the function after the document is ready it still gives the error

**Comment by ravinderk** [comment]
@raftaar1191 PR updated

**Comment by raftaar1191** [comment]
@ravinderk checking it again

**Comment by DevinWalker** [comment]
Thanks @ravinderk

**Pull request merged**
