### PR TITLE
Few more i18n improvments

### PR DESCRIPTION
**Pull request by ramiy**
This time I'm fixing the _x(). Translations with context. Update context text in some places, remove context in other places, and few extra translation string updates.

### CODE REVIEW

**Comment by ramiy** [comment]
The last commit for similar strings based on:

**Comment by DevinWalker** [comment]
Thanks @ramiy - Related to #451

**Comment by DevinWalker** [comment]
How come you're removing usage of `_x()` string explanations? Do you think they add more confusion for translators?

**Comment by ramiy** [comment]
one more:

**Comment by ramiy** [comment]
As for the use of _x() function:

In WordPress core, we use this function when a string is used in many places, but we want one of those strings to have a different meaning. When we add the context function, this string will appear as a separate string in translate.wordpress.org .

**Comment by ramiy** [comment]
one more:

**Comment by ramiy** [comment]
Another similar string merge:



@DevinWalker Here you can see the string with the unneeded context.

**Comment by DevinWalker** [comment]
Oh yeah, I see that. Thanks for the example

**Comment by ramiy** [comment]
few more:





Merge similar strings and remove context functions.

**Comment by DevinWalker** [comment]
This is great, thanks a lot for the effort here.

**Pull request merged**
