### PR TITLE
Mergin to Goals branch. Implements #42

### PR DESCRIPTION
**Pull request by ibndawood**
Hello @DevinWalker, here is the PR to merge to Goals branch. I suggest you to have a look at Git Flow. Its a very effective branching model. http://nvie.com/posts/a-successful-git-branching-model/

### CODE REVIEW

**Comment by DevinWalker** [comment]
Admittedly, I need to get better at that. Thanks for the link, this is a priority to get our workflow setup effectively.

**Comment by DevinWalker** [comment]
What happened to the PR?

**Comment by ibndawood** [comment]
I closed the previous one and this one is to merge to Goals branch.

**Comment by DevinWalker** [comment]
Looking nice so far after some testing!

**Pull request merged**
