### PR TITLE
phpDocs - various updates

### PR DESCRIPTION
**Pull request by ramiy**

### CODE REVIEW

**Comment by DevinWalker** [comment]
Hey @ramiy we just got some time to review this and 

1. Can you ensure periods are removed. Looking through WP core files and PHPdocs it appears it
2. We can use @package instead of @subpackage , because it is going to deprecate soon https://phpdoc.org/docs/latest/references/phpdoc/tags/subpackage.html
3. Ensure all comments are closed properly - @ravinderk said he saw a place where the comment wasn't closed by the link he provided didn't have the line number so I can't reference it. He'll post when he comes back online.

**Comment by ramiy** [comment]
@DevinWalker We already use **@package**, Do you want me to delete all the **@subpackage**?

**Comment by DevinWalker** [comment]
If you could swap out the usage of `@subpackage` to `@package`that'd be great.

**Comment by ramiy** [comment]
Replace this:
```
 * @package     Give
 * @subpackage  Classes/Give_Cron
```

to:
```
 * @package     Give
 * @package     Classes/Give_Cron
```

or:
```
 * @package     Classes/Give_Cron
```

or:
```
 * @package     Give_Cron
```

**Comment by ramiy** [comment]
By the way, WordPress code still use **@subpackage**, they did not deprecated them.

**Comment by DevinWalker** [comment]
@ramiy - let's go with ` * @package     Classes/Give_Cron`

**Pull request merged**
