### PR TITLE
GH#2074 Removed donors tab

### PR DESCRIPTION
**Pull request by Sidsector9**
See #2074 
Deleted files that generated the Donors in Reports

### CODE REVIEW

**Comment by Sidsector9** [comment]
My apologies @DevinWalker, I've made the changes

**Comment by DevinWalker** [comment]
Thanks @Sidsector9 - also remember to submit to the correct release branch that the issue is tied to. In this case, https://github.com/WordImpress/Give/issues/2074 is tied to `release/1.8.14` so the PR would use that as base. Thanks for your contributions!

**Comment by Sidsector9** [comment]
@DevinWalker, I'll keep that in mind henceforth for upcoming contributions.

**Comment by ravinderk** [comment]
@Sidsector9 Keep contributing. 
FYI, I will keep updating default `git branch` to coming release, so any new contributors do not need to think about on which release we are working. When you will create new PR `git` will automatically create PR against coming release.

**KEEP UP GOOD WORK.**

For Ref: https://help.github.com/articles/setting-the-default-branch/

**Pull request merged**
