### PR TITLE
Switch a transaction to a different form

### PR DESCRIPTION
**Pull request by ravinderk**
Related to: https://github.com/WordImpress/Give/issues/429

### CODE REVIEW

**Comment by DevinWalker** [comment]
@ravinderk I'm seeing some broken builds here with:

> Fatal error: Can't use function return value in write context in /home/travis/build/WordImpress/Give/includes/ajax-functions.php on line 411 

https://travis-ci.org/WordImpress/Give/jobs/144727554

Can you check that out for me?

**Comment by ravinderk** [comment]
@DevinWalker Error fixed. You can review this.

**Comment by DevinWalker** [comment]
I'm going to test this out first thing in the morning!

**Comment by ravinderk** [comment]
@DevinWalker Alright.

Thank you

**Comment by DevinWalker** [comment]
I tested it out pretty thoroughly and it's working great. I've brought it up to date and kept your commits intact in this separate PR: https://github.com/WordImpress/Give/pull/761

**Pull request closed without merging**
