### PR TITLE
Add required fields check on step 2 when import from donations

### LINKED ISSUE #2354: IMPORTER: Required fields should be more obvious
## Issue Overview
We should make it obvious which fields are required in order for the import to work. Potentially, the "Import" button would also be greyed out until all required fields have been chosen as well. Doing an alert upon submission is not an awesome user experience.

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to fix #2354 

## How Has This Been Tested?
Have tested this in firefox, chrome as well as in safari 
See the video on how I have tested this
Video Link: https://screencast-o-matic.com/watch/cFnhI7oBgg

## Screenshots (jpeg or gifs if applicable):
image

image

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@mehul0810 
I have update the code and it's being fix can you please kindly review it again

**Comment by mehul0810** [comment]
@raftaar1191 I've tested this PR and the functionality is working fine. However, there are some UI and typos as shown in the screenshot below.

image

**Comment by raftaar1191** [comment]
Thanks @mehul0810 for review the PR 

Have fixed both the issues below is the screenshot 


image

**Comment by ravinderk** [comment]
@raftaar1191 I was able to surpass required field condition. Donation imported successfully but can not see them on donation listing page. Let me know if you have any question.

image

**Comment by raftaar1191** [comment]
@ravinderk can you please share the CSV 

Will like to regenerate this issues at my end too

**Pull request merged**
