### PR TITLE
fix(admin-donation): add delete button on donations page  #2734

### LINKED ISSUE #2734: feat(admin-donation): add delete button to single donation screen
## Issue Overview
There Should an option to delete the Donation from Donation Single Page in Dashboard

image

image

## Expected Behavior
There should a Donation delete button in Donation single page like we have in Donation archived Page

## Current Behavior
No delete button is found

## Todos
- [x] Tests
- [x] Documentation

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://give18.local
Site URL: http://give18.local
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wpgive_
Table Prefix Length: 7
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give18.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.1
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give18.local/donation-confirmation/
Failure Page: http://give18.local/donation-failed/
Donation History Page: http://give18.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###

Give - Manual Donations: ❌ Unlicensed – by WordImpress – 1.2.2

### Other Active Plugins ###

Give - Development Plugin: by Raftaar1191 – 1.0.0
Loco Translate: by Tim Whitlock – 2.0.17
WP Hide & Security Enhancer: by Nsp Code – 1.4.7.6
WPS Hide Login: by Remy Perona for WPServeur – 1.2.1

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.1
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Authorize.net Gateway: by WordImpress – 1.3.2
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.0
Give - Fee Recovery: by WordImpress – 1.3.8
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2.4
Give - Gift Aid: by WordImpress – 1.1
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - MailChimp: by WordImpress – 1.3.7
Give - Paymill Gateway: by WordImpress – 1.1
Give - PDF Receipts: by WordImpress – 2.2.4
Give - Recurring Donations: by WordImpress – 1.5.4
Give - Stripe Gateway: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.3.6
WooCommerce: by Automattic – 3.2.6

### Active MU Plugins ###

wp-hide-loader.php: by  –

### Theme ###

Name: Twenty Seventeen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to fix #2734 

**Notes: This PR contains the code of Modal API PR too so please merge the https://github.com/WordImpress/Give/pull/2981 PR first in to Give release 2.1.0 and then this PR**

## How Has This Been Tested?
Manually Tested 

## Video/Screenshots (jpeg or gifs if applicable):

Video Link: https://screencast-o-matic.com/watch/cFfQIBDMgH

image

image

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
I'm not a big fan of the button hanging out in the middle of the row like that. Needs some design work.

**Comment by raftaar1191** [comment]
@DevinWalker 

We can move the delete button to below two section and I guess moving it on the right side will be a great option 


image

**Comment by DevinWalker** [comment]
## Review Findings

@mathetos they can already delete in bulk on the donation listing screen so I don't think it's a big deal to add the ability to delete the individual donation payment. I just don't want a big glaring button in your face or anywhere that could accidentally be clicked. 

### Solution

Please see this InvisionApp concept: https://invis.io/WPGOUHCBKUX#/289312411_Hover

Basically it's a little mini-trashcan icon that hovers to red when clicked. This is blocked by the merging of the new Modal API.

**Comment by slewisma** [comment]
Adding a user's perspective here. Mixed feelings on this one. I like to easily be able to delete all the donations that were made in Test Mode after testing a new site. I worry about Give Managers and Admins deleting donations easily from an audit and anti-fraud perspective. And I wonder how you will decide what deleting a donation means .... will a delete in Give be a trigger to Zapier for Actions of my choosing? Does a delete in Give tell a payment gateway to cancel a recurring donation? Do you have to prompt for all these decisions in the delete act? Or do you keep it simple and just delete the transaction or transactions chosen and leave any related cleanup to the person who is doing the deleting?

**Comment by DevinWalker** [comment]
Hey @slewisma - let me answer some of your questions:

> I like to easily be able to delete all the donations that were made in Test Mode after testing a new site.

You can do this currently using the bulk option on the donation listing screen but not individually per donation.

> Will a delete in Give be a trigger to Zapier for Actions of my choosing?

Yes if you have a Zap setup for the "Deleted Donation" action.

> Does a delete in Give tell a payment gateway to cancel a recurring donation?

Not at this time, not. Nor does it refund it. I don't think deleting a donation should cancel a subscription. Subscription should be handled differently via the single subscription view. 

> Do you have to prompt for all these decisions in the delete act?

There will be a prompt confirming the admin wants to delete the donation. Not anything for refunding the payment first or anything related to adjusting stats or subscriptions.

> Or do you keep it simple and just delete the transaction or transactions chosen and leave any related cleanup to the person who is doing the deleting?

We keep it pretty simple when deleting. However, we do automatically adjust stats when a donation payment is deleted.

**Pull request merged**
