### PR TITLE
Fix for Issue/249

### LINKED ISSUE #249: `give_require_billing_address` filter is always set to `false`
The `give_require_billing_address` filter (`/includes/process-purchase.php:275`) is `true` by default, but will always be set to `false` because of `give_manual_no_cc_validation()`.

Here is a alternate way to write the function that allows other functions to modify the filtered value:
```
/**
 * Manual Gateway does not need CC billing address validation, so remove it.
 *
 * @since 1.0
 *
 * @param bool $bool
 *
 * @return void
 */
function give_manual_no_cc_validation( $bool ) {
	if ( isset( $_POST['give-gateway'] ) && $_POST['give-gateway'] == 'manual' ) {
		$bool = false;
	}

	return $bool;
}

add_filter( 'give_require_billing_address', 'give_manual_no_cc_validation' );
```

Since the default filtered value is `true`, you will need to add a similar function to any gateways that do not require billing address validation (i.e. PayPal Standard, Offline, etc.).

---

There is also an issue with the Braintree gateway plugin where form validation is not performed via ajax, making it impossible to use the single Form Payment Field `Reveal Upon Click / Modal Window Upon Click` options successfully.

I mention this here because I am sending you an email with a preliminary fix for the Braintree plugin, but it is not complete without being able to also validate the billing address fields.

### PR DESCRIPTION
**Pull request by DevinWalker**
@mathetos @pryley check out this PR to fix #249 

I've tested and it's working well with the gateways I've tested (braintree, offline, paypal standard, manual/test)

### CODE REVIEW

**Comment by mathetos** [comment]
Just tested with Stripe (test keys, but Give in Live Mode) and it failed. Here's the error:

`Warning: Missing argument 1 for give_purchase_form_required_fields(), called in ...\wp-content\plugins\give\includes\process-purchase.php on line 598 and defined in ...\wp-content\plugins\give\includes\process-purchase.php on line 274`

**Comment by DevinWalker** [comment]
@mathetos can you check now?

**Comment by mathetos** [comment]
Looks good now. Used a test credit card number and when Give was LIVE it declined the card, and when I put it in TEST the donation went through perfectly.

**Comment by DevinWalker** [comment]
@mathetos thanks for checking stripe. The issue we're looking for is whether gateways that do NOT require billing fields (address/zip/country) that they do not incorrectly respond back with validation errors saying these fields are required (when they aren't even output). 

We need to confirm:

- [ ] PayPal Standard works
- [ ] Offline Works
- [x ] Stripe Works
- [ ] Manual / Test works
- [ ] PayPal Pro works
- [x] Braintree works
- [ ] Authorize.net works

**Comment by mathetos** [comment]
Updated list: 
- [x] PayPal Standard works*
- [x] Offline Works*
- [x] Stripe Works
- [x] Manual / Test works
- [ ] PayPal Pro works
- [x] Braintree works
- [ ] Authorize.net works
- [ ] Dwolla works*

**Comment by DevinWalker** [comment]
Confirmed Dwolla & PPP

**Comment by DevinWalker** [comment]
Seems pretty solid. I'd like to hear from @pryley

**Comment by DevinWalker** [comment]
Confirmed Authorize just now too

**Comment by pryley** [comment]
It looks good to me.

You could also make $form_id optional in `give_field_is_required()` as it seems to be only the billing address fields that use it (?). That would mean getting the $payment_mode in `give_require_billing_address()` and then a check for only if form_id !== false...or something like that.

**Comment by DevinWalker** [comment]
Thinking future-wise I think it'll be useful to pass the `$form_id` var for form-specific validation.

**Pull request merged**
