### PR TITLE
Composerify

### PR DESCRIPTION
**Pull request by michaelbeil**
#131

### CODE REVIEW

**Comment by DevinWalker** [comment]
Thanks @michaelbeil - question: since we are using other packages like CMB2 - should that also be included as one of our "dependencies"?

**Comment by michaelbeil** [comment]
Well, it looks you are not using CMB2 as a submodule, but are simply pulling in any changes directly, right?

**Comment by DevinWalker** [comment]
No it's not a submodule - since we have a lot of custom fields we created to work for Give we prefer to update it incrementally.

**Comment by michaelbeil** [comment]
You should be good to go then.

If you want to experiment, check out this tut form the guys over at Roots: https://roots.io/using-composer-with-wordpress.

**Comment by DevinWalker** [comment]
Cool thanks!

**Comment by michaelbeil** [comment]
Sure thing.

**Pull request merged**
