### PR TITLE
Fix amount style in form header for larger donation

### PR DESCRIPTION
**Pull request by ravinderk**
**Before Fix**
screen shot 2016-07-20 at 5 06 54 pm

**After Fix**
screen shot 2016-07-20 at 5 13 42 pm

screen shot 2016-07-20 at 5 14 29 pm

Related to: https://github.com/WordImpress/Give/issues/696

### CODE REVIEW

**Comment by DevinWalker** [comment]
I can't reproduce this, which browser are you using?

**Comment by ravinderk** [comment]
@DevinWalker Resize your browser and then test. This bug was appear on small screens.

**Comment by DevinWalker** [comment]
Hmm, still can't... I'd prefer the donation area stay the same size and have the overflow hidden. What do you think?

t5fwzwjzxc

**Comment by DevinWalker** [comment]
My bad, I failed to see your comment on #696 with the NO custom amount setting enabled. Merging.

**Pull request merged**
