### PR TITLE
Implementation of Goals Feature. Issue #42

### PR DESCRIPTION
**Pull request by ibndawood**
Hello @DevinWalker and @mathetos ,

I really like the "Goals" feature. I have implemented it by following the same trail as `price` property of `Give_Donate_Form` class.

Let me know your thoughts.

Thanks

### CODE REVIEW

**Comment by DevinWalker** [comment]
@ibndawood this is a pretty nice PR here and is close to what we want to see in the "Goal" feature of the plugin. Do you have some time to connect and discuss our objectives compared to this PR?

**Comment by ibndawood** [comment]
Here are some screenshots of the implementation:

1. Integration with dashboard columns: 
Image of Dashboard

2. Integration with Add Form Meta Box:
Meta Box

3. The template tags integration:
Template Tags

**Comment by ibndawood** [comment]
Oh sure. How to connect ?

**Comment by DevinWalker** [comment]
Let me discuss what you have here with @mathetos this afternoon and then get back to you. Basically, we were thinking goals would be something like this but more advanced. Allowing users to customize goals beyond a single form with conditional and/or statements. Imagine being able to set a goal per user, per form, and per category/tag, etc.

**Comment by ibndawood** [comment]
Sure. Looking forward to that :)

**Comment by DevinWalker** [comment]
@ibndawood would you mind submitting your PR to this new branch? https://github.com/WordImpress/Give/tree/goals

**Comment by ibndawood** [comment]
Submitted PR to Goals branch. https://github.com/WordImpress/Give/pull/139

**Pull request closed without merging**
