### PR TITLE
Fix bug on current_url retrival

### PR DESCRIPTION
**Pull request by Rahe**
Fix bug for https://github.com/WordImpress/Give/issues/622

### CODE REVIEW

**Comment by DevinWalker** [comment]
Thanks @Rahe 

It looks like this is breaking some unit tests though... https://travis-ci.org/WordImpress/Give/builds/132518886

If you have a chance can you look into that? Otherwise, I'll have to check it out soon.

**Comment by Rahe** [comment]
Wrong variable name :( I Will change the PR

**Comment by Rahe** [comment]
Hello,

I have fixed the variable name ;)

**Comment by DevinWalker** [comment]
Thanks for fixing this... I'm wondering do we need the `untrailingslashit` ? It's breaking some unit tests...

**Comment by Rahe** [comment]
Hello, this is like WordPress is doing it 
https://github.com/WordPress/WordPress/blob/master/wp-includes/nav-menu-template.php#L590

So the tests shouldn't fail :/

**Pull request merged**
