### PR TITLE
Resubmit https://github.com/WordImpress/Give/pull/99

### PR DESCRIPTION
**Pull request by chriscct7**
Just as a side thought: In the future, if you don't close initial pull request, its really easy to actually just pull it up to master. Saves alot of time for contributors

### CODE REVIEW

**Comment by DevinWalker** [comment]
Ok, I wasn't sure how to handle that ;)

**Comment by chriscct7** [comment]
Yep not a problem. It's far easier if the branch stays open. If they aren't a contributor to your plugin in the repo settings, its a tedious manual process to resubmit prs

**Comment by DevinWalker** [comment]
Yeah I've experienced that a bit with my own PRs to other repos... it's neat being on the other side. So much power :bowtie:

**Comment by chriscct7** [comment]
The trick is to use that power wisely. Except on Sundays. No one actually
uses the powers on Sundays. Too much work.

**Comment by DevinWalker** [comment]
Sunday is tough... I see you've been using them quite a bit though https://github.com/chriscct7

**Comment by chriscct7** [comment]
No school on Sundays ;)

**Pull request merged**
