### PR TITLE
Issues 2275

### LINKED ISSUE #2275: Adding the currency of indonesia (IDR)
## Issue Overview
We Need to add Currency for Indonesia as well in the Give Core

## Expected Behavior
Should have Indonesia  currency 

## Current Behavior
We have filter to do that but I think it would be better to add that in Give Core

## Related Issues
https://wordpress.org/support/topic/please-add-currency/

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to resolve #2275 

## How Has This Been Tested?
Manually test by adding the currency 

## Screenshots (jpeg or gifs if applicable):
image

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@ravinderk @DevinWalker 
Please review and merge the PR

**Comment by raftaar1191** [comment]
@ravinderk Need your help with Travis. As builds is getting failed

**Comment by ravinderk** [comment]
@raftaar1191 
1. Please add the unit tests to check all currencies.
2. Please share you testing details.
3. Do you think that `chosen` field will be more helpful to select currency instead of `select`?

@DevinWalker Do you think we can add bitcoin to the core?
for ref: https://github.com/WordImpress/Give/pull/2345/files#diff-5806e141eaa0104339c5325ec46eec73R559

**Comment by raftaar1191** [comment]
1. Please add the unit tests to check all currencies.
-> Adding PHPUnit

2. Please share you testing details.
->I tested it by changing the currency from the Dashboard of Give Core and then in the frontends making a test donation and checking the value in the Dashboard -> Donation

3. Do you think that chosen field will be more helpful to select currency instead of select?
-> Yes, Absolutely. it will be really useful for admin

**Comment by DevinWalker** [comment]
@raftaar1191 these unit tests have been failing after running several times. We need to figure out why that is happening prior to merging this into core. I think it's having a problem looping through all the new currencies added.

**Pull request merged**
