### PR TITLE
Issue/896 deprecate *_Customer_* classes for *_Donor_* classes

### PR DESCRIPTION
**Pull request by DevinWalker**
## Description
Deprecating Give's "Customer" classes in favor for "Donor" classes. #896 

## How Has This Been Tested?
This is _untested_ and should not be merged yet. This PR is ongoing ATM.

## Types of changes
- Code clarity
- Terminology updates

### CODE REVIEW

**Comment by ravinderk** [comment]
@DevinWalker To call deprecated functions we can use `__call` method.
for example:
```
   /**
	 * There are certain responsibility of this function:
	 *  1. handle backward compatibility for deprecated functions
	 *
	 * @since 1.8.8
	 *
	 * @param $name
	 * @param $arguments
	 *
	 * @return mixed
	 */
	public function __call( $name, $arguments ) {
		$deprecated_function_arr = array( 'get_customer_by' );

		if ( in_array( $name, $deprecated_function_arr ) ) {
			switch ( $name ) {
				case 'get_customer_by':
					$field    = ! empty( $arguments[0] ) ? $arguments[0] : 'id';
					$donor_id = ! empty( $arguments[1] ) ? $arguments[1] : 0;

					return $this->get_donor_by( $field, $donor_id );
			}
		}
	}
```

@DevinWalker Let me know what do you think?

**Comment by DevinWalker** [comment]
@ravinderk I like that a lot!

**Comment by DevinWalker** [comment]
@ravinderk good catch

**Comment by ravinderk** [comment]
@DevinWalker this PR looks good to me now.

**Pull request merged**
