### PR TITLE
Assume multiple give dropdown buttons

### LINKED ISSUE #304: Divi Theme and New Shortcode Builder Conflict
**Reported:** https://wordpress.org/support/topic/give-plugin-messing-with-wordpress-text-editor?replies=2#post-7513446

**Screenshots:**

unnamed 1
unnamed

### PR DESCRIPTION
**Pull request by pryley**
Fixes #304 

Multiple wysiwyg editors means multiple give shortcode buttons. We shouldn't use static ID's on elements that may be duplicated, and especially should not target these ID's in JS with the assumption that they are unique.

P.S. Also ran gulp!

### CODE REVIEW

**Comment by pryley** [comment]
@DevinWalker please test.

**Comment by DevinWalker** [comment]
Thanks I'll check this out

**Comment by DevinWalker** [comment]
Hey @pryley I just checked this out and am not seeing the shortcode popup appear when I use the "Text Module" from Divi:

10-8-2015 12-01-53 pm

Did you see it working?

**Comment by DevinWalker** [comment]
@pryley I took another look and it's working. Not sure what was going on before...

**Comment by DevinWalker** [comment]
thanks :)

**Pull request merged**
