### PR TITLE
Auto populate correct donation level when user add amount on checkout page

### PR DESCRIPTION
**Pull request by ravinderk**
Related to : https://github.com/WordImpress/Give/issues/730

### CODE REVIEW

**Comment by DevinWalker** [comment]
I'm seeing some issues here when testing. Check it out:

Here is my form setup:

screen shot 2016-07-22 at 11 30 59 am

When I make a custom test donation after clicking on a multi-level amount, the level is incorrectly set:

injzdfhgtx

**Comment by ravinderk** [comment]
@DevinWalker This issue has been fixed.

donation-issue

**Comment by DevinWalker** [comment]
Thanks @ravinderk I'm seeing an issue here:

screen shot 2016-07-22 at 1 55 19 pm

`( ! ) Notice: Undefined index: give-price-id in /app/public/wp-content/plugins/give/includes/process-purchase.php on line 1084` 

This happens when you make a donation. Here's my donation form setup (very basic):

screen shot 2016-07-22 at 1 55 19 pm

**Comment by ravinderk** [comment]
@DevinWalker Notices has been fixed. You can review this.

**Comment by DevinWalker** [comment]
This is working well now, thanks!

**Pull request merged**
