### PR TITLE
Remove variable that is globally accessible #2663

### LINKED ISSUE #2663: Deprecating the second $_POST parameter
## Issue Overview
We should deprecate the second parameter of this action as this is a global variable which is access able global so we do not need to pass this with parameter 

image

https://github.com/WordImpress/Give/blob/release/2.0/includes/process-donation.php#L66

## Related PR & Issues
https://github.com/WordImpress/Give-Tributes/issues/230
https://github.com/WordImpress/Give-Recurring-Donations/issues/501
https://github.com/WordImpress/Give-Stripe/issues/119
https://github.com/WordImpress/Give-Gift-Aid/issues/86

## Expected Behavior
Should not pass the global access variable through parameter 

## Current Behavior
Passing the $_POST value from parameter 

## Todos
- [x] Tests
- [x] Documentation

## WordPress Environment
<details>
```
### WordPress Environment ###

Home URL: http://give18.local
Site URL: http://give18.local
WP Version: 4.9.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give18.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.0.3
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.55 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.0.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New Donor Registration✔Donor Register✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: GBP
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://give18.local/donation-confirmation/
Failure Page: http://give18.local/donation-failed/
Donation History Page: http://give18.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Active Give Add-ons ###


### Other Active Plugins ###

Give - Development Plugin: by Raftaar1191 – 1.0.0

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2.1
Give - 2Checkout Gateway: by WordImpress – 1.0.2
Give - Authorize.net Gateway: by WordImpress – 1.3.2
Give - AWeber: by WordImpress – 1.0.2
Give - Braintree Gateway: by WordImpress – 1.1.1
Give - CCAvenue Gateway: by WordImpress – 1.0
Give - ConvertKit: by WordImpress – 1.0.1
Give - CSV Toolbox: by WordImpress – 1.0
Give - Display Donors: by WordImpress, LLC – 1.0
Give - Dwolla Gateway: by WordImpress – 1.1.2
Give - Email Reports: by WordImpress – 1.0.2
Give - Fee Recovery: by WordImpress – 1.3.8
Give - Form Countdown: by WordImpress – 1.0
Give - Form Field Manager: by WordImpress – 1.2.4
Give - Gift Aid: by WordImpress – 1.0.0
Give - Google Analytics Donation Tracking: by WordImpress – 1.1.1
Give - MailChimp: by WordImpress – 1.3.7
Give - Manual Donations: by WordImpress – 1.2.2
Give - Paymill Gateway: by WordImpress – 1.1
Give - PDF Receipts: by WordImpress – 2.2.2
Give - Recurring Donations: by WordImpress – 1.5.4
Give - Stripe Gateway: by WordImpress – 1.5.2
Give - Tributes: by WordImpress – 1.3.3

### Theme ###

Name: Twenty Sixteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR to fix #2663 

## How Has This Been Tested?
Manually Tested

## Types of changes
Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by raftaar1191** [comment]
@DevinWalker @ravinderk 

Need to Create a blog post and inform all the developer about this ( That we are removing the second parameter from the do_action of `give_checkout_error_checks ` as this is accessible from the $_POST directly )

**Comment by kevinwhoffman** [comment]
We should not remove the parameter altogether since it would break functionality for any developer relying on it. We should instead follow WordPress core's lead by renaming the deprecated parameter and noting it in the DocBlock.

```php
/**
 * Fires after validating donation form fields.
 *
 * Allow you to hook to donation form errors.
 *
 * @since 1.0
 * @since 2.0.2 Second parameter deprecated in favor of $_POST.
 *
 * @param bool|array $valid_data Validated fields.
 * @param array      $deprecated Deprecated. Use $_POST instead.
 */
do_action( 'give_checkout_error_checks', $valid_data, $deprecated );
```

**Comment by raftaar1191** [comment]
Thanks, @kevinwhoffman ya I love the example.

@DevinWalker @kevinwhoffman 
Just one question what I supposed to passed in $deprecated should I pass NULL to it 

```
do_action( 'give_checkout_error_checks', $valid_data, $deprecated = NULL );
```

**Comment by DevinWalker** [comment]
@raftaar1191 no don't pass null that would basically be the same thing as removing it. Preserve the passed value so it doesn't break things.

**Comment by raftaar1191** [comment]
Thanks @DevinWalker for you reply updated the PR

**Comment by kevinwhoffman** [comment]
Good catch on keeping `$deprecated = $_POST` so that data is still available within any hooked functions.

**Pull request merged**
