### PR TITLE
Issues 2176

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR for issues #2176 

## How Has This Been Tested?
Tested before running gulp and after running gulp

## Screenshots (jpeg or gifs if applicable):
image
image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by raftaar1191** [comment]
@DevinWalker 

Please review and merge the PR

**Comment by ravinderk** [comment]
@raftaar1191 Font size of message is little bigger.

**Comment by raftaar1191** [comment]
@ravinderk Fix Font size & Padding issues 

Please review and merge the PR

image

image

**Comment by ravinderk** [comment]
@raftaar1191 Good Job 👍

**Pull request merged**
