### PR TITLE
Issue/390

### PR DESCRIPTION
**Pull request by pryley**
#390 

image

A couple notes:

1. There is no detection to check if the set amount is less than the custom amount minimum on Edit/Quick Edit form. I decided it was better to leave this in the user's court and only inform the user via the "Set Amount" label on the Edit Form page to make sure the set amount was greater than the custom amount minimum.

2. I'm not convinced that setting the `$minimum_price` variable in the `Give_Donate_Form` object is the correct thing to do. But it's related at times to the form's `$price` so maybe it's fine.

### CODE REVIEW

**Comment by DevinWalker** [comment]
Thanks I'll check it out!

**Comment by DevinWalker** [comment]
I wonder why scrutinizer screwed up

**Comment by pryley** [comment]
I merged your recent changes and adjusted `give-checkout-global` to work with it.

**Comment by DevinWalker** [comment]
Updated PR via: https://github.com/WordImpress/Give/pull/489

**Pull request closed without merging**
