### PR TITLE
GH#2190 Fixed CSS break for fieldset and legend tags

### PR DESCRIPTION
**Pull request by Sidsector9**
See #2190 

## Description
`width: 100%` and `border-bottom` were applied to `legend` tag which was unnecessary so I removed them.

## Screenshot
The render after the CSS fix.
image

### CODE REVIEW

**Comment by kevinwhoffman** [comment]
Some of these styles affect the donation forms. For example, `legend` elements need a bottom border in the donation forms, but not in the profile form. I'm going to note that on the original issue. Thanks.

**Comment by Sidsector9** [comment]
@kevinwhoffman I've updated the CSS specific to the profile editor form.

**Comment by DevinWalker** [comment]
@Sidsector9 I don't see the left margins being lined up very evenly here:

68747470733a2f2f63646e2e706272642e636f2f696d616765732f475138336544482e706e67

Can you take care of that?

**Comment by Sidsector9** [comment]
@DevinWalker that's odd :thinking: Here at my end, they're perfectly aligned as you can see here -
image

Tested on 
 - Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)
 - Mozilla Firefox 56.0 (64-bit)

Can you perform a hard refresh or test it using a different browser and let me know whether the issue still persists?

**Comment by DevinWalker** [comment]
@Sidsector9 I'm looking at your screenshot above where you say:

> The render after the CSS fix.

**Comment by raftaar1191** [comment]
@DevinWalker This issues generated and solved in Give Core Version `1.8.15` 

I just had a check it's working perfectly alright now ( Give Core Version `1.8.16` )
Screenshot: 
image

Just One thing @Sidsector9 @DevinWalker 
image

I can see some small image appearing in your example
It was there already or it has been added now?

**Comment by DevinWalker** [comment]
What do you mean @raftaar1191 - it's already resolved? That image is from an app extension. Don't worry about that. But I'm confused, are you saying this PR is not needed?

**Comment by raftaar1191** [comment]
@DevinWalker I means to say that your comment related to [left margins being lined](https://github.com/WordImpress/Give/pull/2228#issuecomment-338766774) is being solved

**Comment by DevinWalker** [comment]
Looks good!

**Pull request merged**
