### PR TITLE
Hotfix/fix floatlabel on events

### PR DESCRIPTION
**Pull request by pryley**

### CODE REVIEW

**Comment by DevinWalker** [comment]
Sweet

**Comment by DevinWalker** [comment]
Checking it out

**Comment by pryley** [comment]
The only problem I see now is if a user has a form showing twice on the same page (i.e. using the widget). When this happens, the form and form element ID's are duplicated which messes with the form events.

**Comment by DevinWalker** [comment]
Yeah I am seeing issues too. I have it enabled globally and it doesn't seem to be taking effect like it should. Seeing strange behaviour

**Comment by pryley** [comment]
That should do it.

**Comment by DevinWalker** [comment]
Yup, just confirmed it's working great.

**Pull request merged**
