### PR TITLE
Issue/1114

### LINKED ISSUE #1114: Reports UI / UX Improvements
## Issue Overview

screenshot at oct 11 14-55-50

When you select a custom date range the user wants to click on "Refresh Reports" when this isn't the correct button. 
## Possible Solution

Move the placement of the button to the left hand side and update the button text to say "Clear Reports Cache".
## Todos
- [ ] Move button
- [ ] Update button text

### PR DESCRIPTION
**Pull request by kevinwhoffman**
## Description

This PR makes the following changes discussed in #1114:
- Removes dropdown navigation in favor of tabs.
- Moves placement of date controls from bottom-right to top-left.
  - Styles controls in single row to keep UI minimal.
  - Places controls within graph to create better relationship between controls and graph.
- Removes redundant title from bottom of reports
- Updates tab wording and title wording to be consistent.
- Updates column headers to reflect donations instead of purchases.
- Lots of escaping prior to output.
## How Has This Been Tested?
- Tested all report tabs in Chrome, Safari, FireFox.
  - @mathetos Could use your help testing Windows browsers.
- Confirmed all income reports (including Custom) properly filter the graph's data.
### Custom Income Report - Before

1114-income-custom-before-2
### Custom Income Report - After

1114-income-custom-after-2
## Types of changes

Resolves #1114
## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@kevinwhoffman I just checked it out and I'm really liking the tabbed reports.  A few things I noticed when testing:

1. Searching for donors results in being redirected back to the main report tab:



2. The Recurring Donations add-on creates it's own reports, and I'm glad it's tab was also created but when viewing you can see it redirects as well to the first tab when switching timespan. Also the dropdown at the bottom looks pretty bad (this may need some fixing in the add-on itself):

**Comment by kevinwhoffman** [comment]
@DevinWalker I'll address both issues and update the PR. Thanks.

**Comment by kevinwhoffman** [comment]
@DevinWalker The commit I just added fixes the search results so they display in the Donors tab.

## New Issues

- https://github.com/WordImpress/Give-Recurring-Donations/issues/294 - I created a separate issue for formatting the Renewal Donations report since it requires a change in the add-on itself.
- https://github.com/WordImpress/Give/issues/1174 - In general, these Income Reports should all use the same code base. Instead they're currently defined in three different locations, which explains why the new format was not reflected in Renewal Donations. This is a maintenance headache for any future updates to the Reports screens. I documented the redundancy in this new issue.

I recommend we test and merge this PR and handle these new issues separately.

**Comment by kevinwhoffman** [comment]
@DevinWalker The CSS conflict has been addressed. I also added a fallback mechanism to ensure any date-driven reports, whether in Give core or add-ons, will load in the current tab.

**Pull request merged**
