### PR TITLE
Issues/1408

### LINKED ISSUE #1408: Add Upgrade Notice for Version 1.8 db changes
## Issue Overview
Currently we are upgrading form meta fields in bulk rather than in batches. This can lead to timeouts on sites with a large number of donation forms. Rather, we need to upgrade them in batches to prevent any sort of failure due to the number of donation forms. 

## Considerations
- Remote updates using InfiniteWP and Manage WP: all normal WordPress hooks do fire as if it were a manual update on site done by an admin (I confirmed with Vinodh).
- Upgrading via FTP
- Upgrading from early version like `1.3` -> `1.8`

## Todos
- [ ] Create AJAX Batch Upgrade Process
- [ ] Test Upgrade Process

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

This PR will resolve #1408 

## Types of changes

New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by mathetos** [comment]
In case an upgrade fails, is there a way to trigger this process again manually? Like visiting a specific URL in WP-Admin? Or maybe adding a button in "Donations > Settings > Advanced" for running updates again?

This is useful and important for Support in troubleshooting. @DevinWalker what's your thoughts on this?

**Comment by ravinderk** [comment]
@mathetos Before process each upgrade step we are saving them to the database, by this way know that on which step admin quit or from where to resume upgrade.
https://github.com/WordImpress/Give/blob/master/includes/admin/upgrades/upgrades.php#L39

For each Give version before showing any upgrade notice we are checking if there any upgrade we have to resume if yes then admin we see an admin notice and he can start upgrade again.
https://github.com/WordImpress/Give/pull/1462/files#diff-fe0e36d5cf90056ccea283fd3c6daa71R106

for normal upgrade, admin will see a notice like:
screen shot 2017-02-09 at 8 24 52 am

For incomplete upgrade, admin will see a notice like:
 
screen shot 2017-02-09 at 8 25 10 am

**Comment by ravinderk** [comment]
@DevinWalker @mathetos Now admin we see confirmation alert when process upgrade. Let me know if you want to update message.
https://github.com/WordImpress/Give/pull/1462/files#diff-e7704c2df23b9fc3a7715723ec4b0758R336

4mcgmw68d9

**Comment by mathetos** [comment]
@ravinderk it's a good idea. But can we do it in the WordPress Core modal (via backbone I believe) instead of the browser alert?

Here's the wording I'd suggest:

> Please make sure to create a database backup before initiating the upgrade.
> BUTTONS: Cancel | I have a backup already. Start Upgrade process.

**Comment by DevinWalker** [comment]
@mathetos let's just do a JS confirm window for now then the modal in the future. We'll need a modal class to make it easily usable throughout the wp-admin. For instance, we also want a modal on deactivation #648

**Comment by mathetos** [comment]
Sounds good.

**Pull request merged**
