### PR TITLE
Issues 1050

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
Fix issue #1050

## How Has This Been Tested?
Manually tested

## Types of changes
New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@raftaar1191 I'm seeing the following issue when testing:

**Comment by raftaar1191** [comment]
@DevinWalker 

Fixed

**Comment by DevinWalker** [comment]
@raftaar1191 I'm seeing issues with the `*` required asterisk displaying conditionally properly. For certain countries the field needs to have the required symbol. 

See for example if I change from US to another country and back:



The required symbol should appear again.

**Comment by raftaar1191** [comment]
@DevinWalker 

Fixed

**Comment by DevinWalker** [comment]
Thanks @raftaar1191 - can you ensure this branch only has the changes you made for the issue? I'm seeing a bunch of other unrelated commits.

**Comment by raftaar1191** [comment]
@DevinWalker 

Done

**Comment by DevinWalker** [comment]
@raftaar1191 would you mind bringing this up to date with the `release/1.8.12` branch so the unit tests pass?

**Comment by raftaar1191** [comment]
@DevinWalker 

Done & all the unit test has being passed

**Comment by DevinWalker** [comment]
Thanks @raftaar1191 good job on this one.

**Pull request merged**
