### PR TITLE
Issues/281

### LINKED ISSUE #281: Design and develop new donation form creation UI
The metaboxes are starting to get a bit unwieldy causing users to scroll further and further down the page. I propose customizing the metaboxes on the Give Forms single admin pages with tab functionality like so: 

give-admin-form-metabox-tabs

Thoughts?

### PR DESCRIPTION
**Pull request by ravinderk**
## Description

1. New metabox setting broke in some new tabs ( Some tab rename also ).
2. Some setting fields is converted from select to radio field ( with backward compatibility ).

## Motivation and Context

This pr will fix #281.

## How Has This Been Tested?

I tested following:
- [x] Metabox settings backward compatibility
- [x] Frontend donation form display [for example: Offline donation, terms & conditions and floating labels].
- [x] Various style and javascript related changes in metabox panel. **Note: Recurring donation addon javascript is not working with new metabox, so we have to update addon javascript.**
- [x] Offline donation and terms & conditions tested by plaing donations.

## Screenshots (jpeg or gifs if applicable):
wj2iinxija

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ramiy** [comment]
@ravinderk We can update all Give addons, to set minimum required Give version to 1.7. This way when they update addons, we force them to update Give Core to the latest version, otherwise they will see an admin notice.

Would that help preventing the backward compatibility issues you mentioned?

**Comment by ravinderk** [comment]
@ramiy  These changes will be in `release 1.8`. **Backward compatibility issues is only with javascript** (php side working fine) means if developer added javascript code depend on cmb2 dom ( class, id ), then there javascript will not work with new setting api dom. That means user will able to see all setting field, they will not conditionally hide on basis of javascript.

cmb2 plugin setting either in core or in addon will be load automatically with new setting api.
https://github.com/WordImpress/Give/blob/release/1.8/includes/admin/settings/class-settings-cmb2-backward-compatibility.php
For metabox setting, developer can add there own setting by separate post metabox ( for example FFM ) or they can use old setting filters ( For example Recurring donation ). So setting is load seamlessly.

We can write a post as @DevinWalker suggested to educate third party plugin developer to test there there addon with `release 1.8` and fix there possible bugs or to learn about new setting. we have example plugin here https://github.com/WordImpress/Give-Settings-API-Example.

And Yes, for In house Give addon we can encourage user to update to `release 1.8` to prevent users from any possible future issue.

**Comment by DevinWalker** [comment]
## Change requests

I tested the code and it's working great. I just have a few change requests:

1. Please ensure when a new form is created there is a default level already in place when the user switches to "multi-level"
new-form-default-level-needed

2. Please change the guest donation checkbox to a radio like displayed in the wireframes:
radio1

3. The default option for new forms should be the global option:
new-form-terms-default

4. The default option for new forms should be the global option:
offline

**Comment by ravinderk** [comment]
@DevinWalker All four point changes done.

**Comment by DevinWalker** [comment]
The `Floating Form Labels` should also be set to "Global Option":

screenshot at sep 28 10-51-35

**Comment by DevinWalker** [comment]
The form content field should also default to "no"
no

**Comment by ravinderk** [comment]
@DevinWalker Above issue has been fixed and I also added db upgrade for form metadata for new settings ( As we discussed on slack ).

**Pull request merged**
