### PR TITLE
Create give-sv_SE.po

### PR DESCRIPTION
**Pull request by mepmepmep**
Add translation file (.po) for Swedish

### CODE REVIEW

**Comment by mepmepmep** [comment]
Thats it I suppose, or?

**Comment by DevinWalker** [comment]
Nice!  You got it. Can you add the .mo file as well?

**Comment by DevinWalker** [comment]
You don't necessarily "upload" the files, but rather you "commit" them... which uploads it in the process to the GitHub repo you commit to when you "push" it. 

Git can take a little bit to get used to but it looks like you're well on your way!

**Comment by mepmepmep** [comment]
So upload is not possible, just source code paste.. Ok, lets see if I can get the source out of the .mo file then.

**Comment by DevinWalker** [comment]
:+1:

**Pull request merged**
