### PR TITLE
refactor(comment): create custom comment table #3627

### LINKED ISSUE #3627: refactor(comment): create custom comment table
## User Story
Give uses WordPress comment functionality. In Give, the comment is mostly used as a note for record activity of donor or donation and donor comment (if enabled): Few plugins start flagging these comment a spam, so in some case, donation process but donor does not notify successfully that means they land on error page instead of donation receipt page.

To prevent this issue we will create a custom comment table to store donation and donor activity.

# ToDo
- [x] Custom Table
   - [x] Create custom table
   - [x] Add helper functions
   - [ ] Add comment query caching ( not improtant, becuase comment query is not expensing and for now only query for comment on donation detail page )
- [x] Add DB upgrade 
- [x] Review backward compatibility
- [x] Testing
   - [x] Review DB upgrade
   - [x] Donor wall shortcode
   - [x] GDPR plugin (after db upgrade)
   - [x] Mojo Market place plugin (after db upgrade)
   - [x] Addons 
        - [x] Manual Donation
        - [x] Stripe
        - [x] Paypal Pro
        - [x] Recurring
         Note: most payment gateways uses `give_insert_payment_note helper` function.
- [ ] Write developer blog post

### PR DESCRIPTION
**Pull request by ravinderk**
## Description
This pr will resolve #3627

## How Has This Been Tested?
Check  `testing` todo list under `Todo`  heading in issue description.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by ravinderk** [comment]
@DevinWalker This Pr is still in `In Progress` because I am testing and updating code. I will add you as a reviewer when I am done.

**Comment by DevinWalker** [comment]
@raftaar1191 please make it a priority to test this when you get online.

**Comment by raftaar1191** [comment]
## Finding
At the time of sending the Donor Note from dashboard getting PHP notices 

Video Link: https://screencast-o-matic.com/watch/cFQIrsqdpa

image


## Debug log
<details>
[13-Sep-2018 21:51:38 UTC] PHP Notice:  Trying to get property of non-object in /app/public/wp-content/plugins/Give/includes/emails/class-give-email-tags.php on line 1503
[13-Sep-2018 21:51:38 UTC] PHP Stack trace:
[13-Sep-2018 21:51:38 UTC] PHP   1. {main}() /app/public/wp-admin/admin-ajax.php:0
[13-Sep-2018 21:51:38 UTC] PHP   2. do_action() /app/public/wp-admin/admin-ajax.php:100
[13-Sep-2018 21:51:38 UTC] PHP   3. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[13-Sep-2018 21:51:38 UTC] PHP   4. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[13-Sep-2018 21:51:38 UTC] PHP   5. give_ajax_store_payment_note() /app/public/wp-includes/class-wp-hook.php:286
[13-Sep-2018 21:51:38 UTC] PHP   6. do_action() /app/public/wp-content/plugins/Give/includes/admin/payments/actions.php:497
[13-Sep-2018 21:51:38 UTC] PHP   7. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[13-Sep-2018 21:51:38 UTC] PHP   8. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:310
[13-Sep-2018 21:51:38 UTC] PHP   9. Give_Donor_Note_Email->send_note() /app/public/wp-includes/class-wp-hook.php:286
[13-Sep-2018 21:51:38 UTC] PHP  10. Give_Email_Notification->send_email_notification() /app/public/wp-content/plugins/Give/includes/admin/emails/class-donor-note-email.php:78
[13-Sep-2018 21:51:38 UTC] PHP  11. give_do_email_tags() /app/public/wp-content/plugins/Give/includes/admin/emails/abstract-email-notification.php:793
[13-Sep-2018 21:51:38 UTC] PHP  12. Give_Email_Template_Tags->do_tags() /app/public/wp-content/plugins/Give/includes/emails/class-give-email-tags.php:300
[13-Sep-2018 21:51:38 UTC] PHP  13. preg_replace_callback() /app/public/wp-content/plugins/Give/includes/emails/class-give-email-tags.php:168
[13-Sep-2018 21:51:38 UTC] PHP  14. Give_Email_Template_Tags->do_tag() /app/public/wp-content/plugins/Give/includes/emails/class-give-email-tags.php:168
[13-Sep-2018 21:51:38 UTC] PHP  15. give_email_tag_donor_note() /app/public/wp-content/plugins/Give/includes/emails/class-give-email-tags.php:194

</details>

**Comment by raftaar1191** [comment]
## Finding
The user ID is missing from the wp_comment table as well as from give_comment table to

We should update the user_id first in a wp_comment table and then update the update the DB so that everything works well 

image

image

**Comment by raftaar1191** [comment]
I guess we should create a new issue for this but not sure so adding this here only. if feel should create a separate issue for this then please create it @ravinderk 


At the time of exporting the donation, I do not see any columns that display `Donor Comments`

image

**Comment by ravinderk** [comment]
@raftaar1191 
1. Resolved
2. I think we store `user_id` when we create in a comment in the old and new comment table. You will see user_id `0` for comments which done by code instead of a real user. for example, we add a comment when donation status changes.
3. Create a separate issue for https://github.com/WordImpress/Give/pull/3659#issuecomment-421173768

**Pull request merged**
