### PR TITLE
Edited the WooCommerce section

### PR DESCRIPTION
**Pull request by michaelbeil**

### CODE REVIEW

**Comment by DevinWalker** [comment]
What exactly changed here?

**Comment by DevinWalker** [comment]
@michaelbeil any update?

**Comment by michaelbeil** [comment]
oh strange, hang on ...

**Comment by michaelbeil** [comment]
see https://www.diffchecker.com/omn8km6l

**Comment by DevinWalker** [comment]
Hey that's cool!

**Comment by DevinWalker** [comment]
Thanks :)

**Comment by michaelbeil** [comment]
💎 you betcha bottom dollar der! ™

**Pull request merged**
