### PR TITLE
Issues 2140

### PR DESCRIPTION
**Pull request by raftaar1191**
## Description
PR for issues #2140 

## How Has This Been Tested?
Tested  by add `&give-message=email_sent` on each menu and submenu of Give Core plugin 
Example: `http://SITENAME/wp-admin/edit.php?post_type=give_forms&page=give-settings&give-message=email_sent`

## Screenshots (jpeg or gifs if applicable):
image

image

## Types of changes
Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by raftaar1191** [comment]
@ravinderk @DevinWalker 

Please review this PR and merge

**Comment by DevinWalker** [comment]
Works well, thanks

**Comment by DevinWalker** [comment]
Good job also testing with Manual Donations

**Comment by raftaar1191** [comment]
Thanks @DevinWalker

**Pull request merged**
