### PR TITLE
Handle lack of customer id more gracefully

### PR DESCRIPTION
**Pull request by davisshaver**

### CODE REVIEW

**Comment by mathetos** [comment]
Definitely kosher. We love Pull Requests! Just easier to know what to test for when there's some context given in the description.

@DevinWalker will look it over and deal with the merge if it's appropriate.

Thanks for reaching out!

**Comment by mathetos** [comment]
@davisshaver Can you explain step-by-step how we can reproduce the `id` error you experienced so we can duplicate it and test your fix?

**Comment by DevinWalker** [comment]
This is pretty close what I'd do... merging and adjusting. Thanks!

**Comment by davisshaver** [comment]
:rocket: – thanks @DevinWalker, happy holidays!

**Pull request merged**
