### PR TITLE
refactor(activation-banner): show activated add-on in tab view.

### PR DESCRIPTION
**Pull request by emgk**
## Description
This PR #2903 

## How Has This Been Tested?
- Manually.

#### When two or more add-on are activated:
multi

#### When single add-on is activated:
screenshot-gwp local-2018 03 16-18-20-15

#### Types of changes
 Bug fix (non-breaking change which fixes an issue) 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@emgk this is nice work. A few items after reviewing:

### Whitespace 

We need to figure out a way to resolve this white space problem when you have a bunch of add-ons installed:




### Functionality 

I was having an issue with a single add-on banner displaying. None of mine displayed when activating. 

1. See the video for the results of testing on my existing `give.test` install: https://goo.gl/vh7U2i
2. See the video for testing on a `fresh` install: https://goo.gl/K2dPrj

**Comment by DevinWalker** [comment]
@emgk please update me on this issue. To address the whitespace issue let's just set a max-height on it with the ability to scroll down the tabs if it exceeds more than four new add-ons activated.

**Comment by emgk** [comment]
Hi @DevinWalker I have updated this PR as per your requested changes.

### Screenshots
#### Cover blank space with same tab design:
screenshot-givefressinstall local-2018 03 20-18-35-42

#### Multiple addons are activated.
ezgif-3-4ca6ddde43


### Video: 
http://www.screencast.com/t/Lo5aAzlA

**Comment by emgk** [comment]
@DevinWalker I have fixed these points.

- Fixed add-on description issue. 
- Removed `text-transform` on Add-on title. 
- Don't show four add-on, reduced `max-height` to show only three add-on in tab list view.

**Comment by emgk** [comment]
## Slack Call Summary
**_Participants_**: @emgk @DevinWalker 
**_Topic_**: Banner display when activate/deactivate give add-on.
**_Result_**: Only add-on activated recently should be appear in activation banner and add-on already dismissed shouldn't be appear.

**Pull request merged**
